Repository Frame-in-Puzzle/Puzzle-Server, pull requests merged in 2022-02, with the labels that each got.

#15 Feature/user test code
  src/main/java/com/server/Puzzle/domain/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/global/security/authentication/CustomUserDetailsService.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#16 Board - post 기능에서 사진을 추가할 수 있는 기능 추가
  build.gradle
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardFile.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFileRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/global/config/aws/AwsS3Config.java
  src/main/java/com/server/Puzzle/global/util/AwsS3Util.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#17 이미지 업로드 기능 추가
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardFile.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardImage.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/global/util/AwsS3Util.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 👀 In Review, 🧙🏻‍♂️kyungJun

#18 게시글 등록 기능 이미지도 등록이 가능하도록 변경
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#19 게시물 수정 기능 보완
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/CorrectionPostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFileRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/global/util/AwsS3Util.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#21 게시물 작성기능에서 fields 와 languages를 저장할 수 있도록 수정
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardField.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardLanguage.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFieldRepository.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardLanguageRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#22 게시물 수정기능 에서 Languages 와 Fields 를 수정할 수 있도록 변경
  src/main/java/com/server/Puzzle/domain/board/dto/request/CorrectionPostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFieldRepository.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardLanguageRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#23 게시물 전체 조회 기능 추가 + BaseTimeEntity를 사용할 수 있도록 활성화
  src/main/java/com/server/Puzzle/PuzzleApplication.java
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardField.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetAllResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#24 게시물 단일 조회 기능 추가
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetAllPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#26 게시글 삭제 기능 구현
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#29 Feature/user
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#30 Feature/exception
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/global/exception/CustomException.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
  src/main/java/com/server/Puzzle/global/exception/ErrorResponse.java
  src/main/java/com/server/Puzzle/global/exception/controller/GlobalExceptionHandler.java
  src/main/java/com/server/Puzzle/global/security/authentication/CustomUserDetailsService.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Puzzle/global/util/CurrentUserUtil.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#32 BoardController Response 방식 변경
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#33 Feature/response
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/global/response/ResponseService.java
  src/main/java/com/server/Puzzle/global/response/result/CommonResult.java
  src/main/java/com/server/Puzzle/global/response/result/ListResult.java
  src/main/java/com/server/Puzzle/global/response/result/SingleResult.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#34 Feature/exception
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
  src/main/java/com/server/Puzzle/global/exception/ErrorResponse.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtExceptionFilter.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#35 프로젝트 합류 요청 기능 추가
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendRepository.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
Labels: Build Success, 👀 In Review, 🧙🏻‍♂️kyungJun

#36 [DELETE] 불필요한 코드 삭제
  src/main/java/com/server/Puzzle/domain/oauth2/controller/OauthController.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#37 [ADD] Exception 대신 JwtException, ServletException 추가
  src/main/java/com/server/Puzzle/global/security/jwt/JwtExceptionFilter.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#38 Feature/exception
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/global/exception/controller/GlobalExceptionHandler.java
  src/main/java/com/server/Puzzle/global/exception/controller/UnknownExceptionHandler.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtExceptionFilter.java
  src/main/java/com/server/Puzzle/global/util/CurrentUserUtil.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#39 Feature/user
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/domain/UserLanguage.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserInfoDto.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserUpdateDto.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserLanguageRepository.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/ProfileService.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#40 Feature/user
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/domain/UserLanguage.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserInfoDto.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserResponseDto.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepository.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserRepository.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/ProfileService.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#41 [ADD] GenerateUser
  src/main/java/com/server/Puzzle/global/dev_config/GenerateUser.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#43 Feature/user
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/global/dev_config/GenerateUser.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#44 게시글 전체조회 URL 변경
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#45 프로젝트 신청 상태 변경
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/domain/AttendStatus.java
  src/main/java/com/server/Puzzle/domain/attend/dto/request/PatchAttendRequest.java
  src/main/java/com/server/Puzzle/domain/attend/dto/response/GetAllAttendResponse.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#46 deleteAttend 기능 개발
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun
