Repository Frame-in-Puzzle/Puzzle-Server, pull requests merged in 2022-01, with the labels that each got.

#3 application.yml 파일 ignore
  .gitignore
  src/main/resources/application.properties
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#4 개발 시작 전 초기 엔티티 세팅 및 파일구조 세팅
  build.gradle
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardField.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardImage.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardLanguage.java
  src/main/java/com/server/Puzzle/domain/board/enumType/Purpose.java
  src/main/java/com/server/Puzzle/domain/board/enumType/Status.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/domain/UserLanguage.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/UserService.java
  src/main/java/com/server/Puzzle/global/config/querydsl/QueryDslConfig.java
  src/main/java/com/server/Puzzle/global/config/swagger/SwaggerConfig.java
  src/main/java/com/server/Puzzle/global/config/web/WebConfig.java
  src/main/java/com/server/Puzzle/global/entity/BaseTimeEntity.java
  src/main/java/com/server/Puzzle/global/enumType/Field.java
  src/main/java/com/server/Puzzle/global/enumType/Language.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
Labels: Build Success, 🙆🏻‍♂️ Done, 🧙🏻‍♂️kyungJun

#5 Feature/oauth2
  .gitignore
  build.gradle
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/enumType/Field.java
  src/main/java/com/server/Puzzle/domain/user/enumType/OauthAttributes.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/OauthProperties.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/dto/LoginResponse.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/dto/OauthTokenResponse.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/service/OauthService.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserRepository.java
  src/main/java/com/server/Puzzle/global/config/security/authentication/CustomUserDetailsService.java
  src/main/java/com/server/Puzzle/global/config/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Puzzle/global/config/security/jwt/JwtTokenFilterConfiguer.java
  src/main/java/com/server/Puzzle/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Puzzle/global/enumType/Role.java
Labels: 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#6 Feature/oauth2
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#7 (CurrentUser) getCurrentName, getCurrentUser create
  src/main/java/com/server/Puzzle/global/config/security/authentication/CurrentUser.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#8 Feature/oauth2
  src/main/java/com/server/Puzzle/domain/user/oauth2/service/OauthService.java
  src/main/java/com/server/Puzzle/global/security/authentication/CustomUserDetailsService.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenFilterConfiguer.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Puzzle/global/util/CurrentUserUtil.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#9 Feature/login
  src/main/java/com/server/Puzzle/domain/oauth2/config/OauthAttributes.java
  src/main/java/com/server/Puzzle/domain/oauth2/config/OauthProperties.java
  src/main/java/com/server/Puzzle/domain/oauth2/controller/OauthController.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/LoginResponse.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/OauthCode.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/OauthTokenResponse.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/OauthService.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/enumType/OauthAttributes.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/dto/LoginResponse.java
  src/main/java/com/server/Puzzle/domain/user/oauth2/dto/OauthTokenResponse.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserRepository.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Puzzle/global/util/CurrentUserUtil.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#10 Feature/oauth2
  src/main/java/com/server/Puzzle/domain/oauth2/controller/OauthController.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/OauthTokenResponse.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#11 Feature/oauth2
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenProvider.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#12 Feature/oauth2
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
Labels: 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#13 게시물 작성 기능 구현
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun
