Repository Frame-in-Puzzle/Puzzle-Server, pull requests merged in 2022-03, with the labels that each got.

#47 게시글 쪽 레거시 코드 수정
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetAllPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardCustomRepository.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#50 langauge 변경에 따른 테스트 코드 수정
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#53 Board post 기능 테스트 코드 작성
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#54 게시물 단일 조회 테스트 코드 작성
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#56 게시물 수정 테스트 코드 작성
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#55 프로필 조회 테스트 작성, 프로필 조회 예외처리 추가
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#57 BoardServiceTest 게시물 전체 조회 테스트 코드 추가
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#58 BoardServiceTest 게시물 삭제 테스트 코드 작성
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#60 게시물 태그 조회 테스트 코드 작성
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#59 프로필 수정, 로그아웃 테스트 작성
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserUpdateDto.java
  src/main/java/com/server/Puzzle/global/exception/collection/UserNotFoundException.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#62 유저 리팩토링
  src/main/java/com/server/Puzzle/domain/user/dto/MyBoardResponse.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
Labels: Build Success, 🙆🏻‍♂️ Done, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#61 회원탈퇴 테스트 작성
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#64 Feature/user
  src/main/java/com/server/Puzzle/domain/oauth2/dto/LoginResponse.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/global/dev_config/GenerateUser.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#63 프로젝트 참가 신청 테스트 코드 작성
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, 🙆🏻‍♂️ Done, 🧙🏻‍♂️kyungJun

#66 [Update] AttendServiceTest 프로젝트 참가 신청 전체 조회 테스트
  src/test/java/com/server/Puzzle/controller/board/BoardControllerTest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#65 oauth 정보 업데이트 기능 삭제 / isFirstVisited 적용
  src/main/java/com/server/Puzzle/domain/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserRepository.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#68 로그인 예외처리 추가
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#69 getPost의 반환값 createdAt 까지 반환하도록 수정
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#70 첫 방문 프로필 정보등록 예외처리
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/UserService.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#71 url 수정
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/global/config/swagger/SwaggerConfig.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#72 코드 리팩토링
  src/main/java/com/server/Puzzle/domain/oauth2/controller/OauthController.java
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserBoardResponse.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/ProfileService.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#73 patchAttend 테스트 코드 작성
  src/main/java/com/server/Puzzle/domain/attend/dto/request/PatchAttendRequest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#74 프로젝트 참가 신청 수정 기능 수정
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/dto/request/PatchAttendRequest.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepository.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#76 Feature/profile
  src/main/java/com/server/Puzzle/domain/user/dto/UserBoardResponse.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#75 프로젝트 참가 신청 취소 / 삭제 기능 수정 + 테스트 코드 작성
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#77 테스트 코드 em.close() 삭제
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#78 토큰 재발급 기능 추가
  src/main/java/com/server/Puzzle/domain/user/controller/TokenController.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserRepository.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/UserService.java
  src/main/java/com/server/Puzzle/global/dev_config/GenerateUser.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#79 에러코드의 메시지를 한글로 변경
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#80 DisplayName 한글로 변경
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#81 게시글을 찾을 수 없을 때 익셉션 테스트
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#82 테스트 메소드 이름 변경
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#83 BoardExceptionTest getPost 에서 BOARD NOT FOUND 가 잘 터지는지 테스트코드 작성
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#84 deletePost 에서 BOARD NOT FOUND 가 잘 터지는지 테스트코드를 작성
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#85 deletePost 에서 BOARD_NOT_HAVE_PERMISSION 가 잘 터지는지 테스트코드 작성
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#86 HealthCheckController health Check 컨트롤러 추가
  src/main/java/com/server/Puzzle/global/controller/HealthCheckController.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#87 AttendStatus 디렉토리 위치 변경
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/dto/request/PatchAttendRequest.java
  src/main/java/com/server/Puzzle/domain/attend/dto/response/GetAllAttendResponse.java
  src/main/java/com/server/Puzzle/domain/attend/enumtype/AttendStatus.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#88 토큰 재발급 api 수정 / 토큰 재발급 테스트 추가
  src/main/java/com/server/Puzzle/domain/user/controller/TokenController.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/TokenServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/TokenService.java
  src/main/java/com/server/Puzzle/domain/user/service/UserService.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#89 SecurityConfig health Check url permitAll 로 변경
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#90 개발, 운영 환경의 프로필 분리
  .gitignore
  src/main/java/com/server/Puzzle/global/dev_config/GenerateUser.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#91 수동 prettier
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/domain/AttendLanguage.java
  src/main/java/com/server/Puzzle/domain/attend/dto/request/PatchAttendRequest.java
  src/main/java/com/server/Puzzle/domain/attend/enumtype/AttendStatus.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardFile.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardLanguage.java
  src/main/java/com/server/Puzzle/domain/board/enumType/Purpose.java
  src/main/java/com/server/Puzzle/domain/board/enumType/Status.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFieldRepository.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFileRepository.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardLanguageRepository.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/global/config/aws/AwsS3Config.java
  src/main/java/com/server/Puzzle/global/config/dev/GenerateUser.java
  src/main/java/com/server/Puzzle/global/config/querydsl/QueryDslConfig.java
  src/main/java/com/server/Puzzle/global/config/swagger/SwaggerConfig.java
  src/main/java/com/server/Puzzle/global/config/web/WebConfig.java
  src/main/java/com/server/Puzzle/global/controller/HealthCheckController.java
  src/main/java/com/server/Puzzle/global/entity/BaseTimeEntity.java
  src/main/java/com/server/Puzzle/global/enumType/Field.java
  src/main/java/com/server/Puzzle/global/enumType/Language.java
  src/main/java/com/server/Puzzle/global/enumType/Role.java
  src/main/java/com/server/Puzzle/global/exception/CustomException.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
  src/main/java/com/server/Puzzle/global/exception/ErrorResponse.java
  src/main/java/com/server/Puzzle/global/exception/collection/UserNotFoundException.java
  src/main/java/com/server/Puzzle/global/exception/controller/GlobalExceptionHandler.java
  src/main/java/com/server/Puzzle/global/exception/controller/UnknownExceptionHandler.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
  src/main/java/com/server/Puzzle/global/security/authentication/CustomUserDetailsService.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtExceptionFilter.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenFilterConfiguer.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Puzzle/global/util/CurrentUserUtil.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#92 [PRETTIER] add prettier !!
  src/main/java/com/server/Puzzle/domain/oauth2/config/OauthAttributes.java
  src/main/java/com/server/Puzzle/domain/oauth2/config/OauthProperties.java
  src/main/java/com/server/Puzzle/domain/oauth2/controller/OauthController.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/LoginResponse.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/OauthCode.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/OauthTokenResponse.java
  src/main/java/com/server/Puzzle/domain/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/OauthService.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/controller/TokenController.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/domain/UserLanguage.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserBoardResponse.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserUpdateDto.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepository.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserLanguageRepository.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserRepository.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/TokenServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/ProfileService.java
  src/main/java/com/server/Puzzle/domain/user/service/TokenService.java
  src/main/java/com/server/Puzzle/domain/user/service/UserService.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#93 s3 dev, prod 환경 분리
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#94 deletePost swagger에서 토큰을 받을 수 있도록 변경
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#96 유저 작성글 조회 분야와 목적 추가
  src/main/java/com/server/Puzzle/domain/user/dto/UserBoardResponse.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#97 cors url 와일드카드 해제
  src/main/java/com/server/Puzzle/global/config/web/WebConfig.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#98 mariadb 의존성 추가
  build.gradle
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#99 GenerateUser imageUrl 추가
  src/main/java/com/server/Puzzle/global/config/dev/GenerateUser.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#100 url 관련 변경사항
  src/main/java/com/server/Puzzle/global/config/swagger/SwaggerConfig.java
  src/main/java/com/server/Puzzle/global/config/web/WebConfig.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#101 attendLanguage 엔티티 삭제
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/domain/AttendLanguage.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendLanguageRepository.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun
