Repository Frame-in-Puzzle/Puzzle-Server, pull requests merged in 2022-04, with the labels that each got.

#102 권한 변경 / 접근 권한 설정
  src/main/java/com/server/Puzzle/domain/oauth2/dto/UserProfile.java
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/controller/TokenController.java
  src/main/java/com/server/Puzzle/domain/user/domain/Roles.java
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/domain/user/dto/RolesProfile.java
  src/main/java/com/server/Puzzle/domain/user/repository/RolesRepository.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/global/config/dev/GenerateUser.java
  src/main/java/com/server/Puzzle/global/enumType/Role.java
  src/main/java/com/server/Puzzle/global/security/SecurityConfig.java
  src/main/java/com/server/Puzzle/global/security/jwt/JwtTokenProvider.java
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#104 Feature/test
  src/test/java/com/server/Puzzle/exception/user/UserExceptionTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#105 update cors
  src/main/java/com/server/Puzzle/global/config/web/WebConfig.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#106 Develop
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/global/config/web/WebConfig.java
  src/test/java/com/server/Puzzle/exception/user/UserExceptionTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🧙🏻‍♂️kyungJun

#107 게시물 태그조회 에서 Purpose 와 Status 를 전체조회 할 수 있게 변경
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/enumType/Purpose.java
  src/main/java/com/server/Puzzle/domain/board/enumType/Status.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardCustomRepositoryImpl.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#108 Attend 일부 기능 캡슐화
  src/main/java/com/server/Puzzle/domain/attend/domain/Attend.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#109 Feature/profile
  src/main/java/com/server/Puzzle/domain/user/dto/UserUpdateDto.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#110 메소드 이름 변경
  src/main/java/com/server/Puzzle/domain/oauth2/service/impl/OauthServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️ hyunin

#111 프로필 이미지 변경 api 개발, board content length 변경
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/dto/ProfileUpdateDto.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/ProfileService.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#112 프로젝트 참가 신청 상태를 확인하는 로직 추가
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/domain/board/enumType/IsAttendStatus.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun
