Repository Frame-in-Puzzle/Puzzle-Server, pull requests merged in 2022-06, with the labels that each got.

#113 게시글 소개 로직 변경으로 인한 코드 수정
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/CorrectionPostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetAllPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostByTagResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
Labels: bug, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#115 [UPD] 검증식 변경
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#116 프론트 컴포넌트 이슈로 인한 deleteAttend 로직 변경
  src/main/java/com/server/Puzzle/domain/attend/controller/AttendController.java
  src/main/java/com/server/Puzzle/domain/attend/dto/response/FindAllAttendResponse.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepository.java
  src/main/java/com/server/Puzzle/domain/attend/repository/AttendCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/attend/service/AttendService.java
  src/main/java/com/server/Puzzle/domain/attend/service/Impl/AttendServiceImpl.java
  src/main/java/com/server/Puzzle/global/exception/ErrorCode.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#120 게시글 자동 추가
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
  src/main/java/com/server/Puzzle/global/config/dev/GenerateUser.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#121 Feature/refactoring
  src/main/java/com/server/Puzzle/domain/oauth2/controller/OauthController.java
  src/main/java/com/server/Puzzle/domain/user/controller/ProfileController.java
  src/main/java/com/server/Puzzle/domain/user/controller/TokenController.java
  src/main/java/com/server/Puzzle/domain/user/controller/UserController.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserProfileResponse.java
  src/main/java/com/server/Puzzle/domain/user/dto/UserUpdateDto.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepository.java
  src/main/java/com/server/Puzzle/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/ProfileService.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#123 테스트 커버리지 관리를 위한 jacoco 도입
  build.gradle
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#125 Mockito 를 활용한 BoardController 의 테스트 케이스 작성
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/test/java/com/server/Puzzle/controller/board/BoardControllerTest.java
  src/test/resources/PuzzleLogo.png
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun

#124 mockMvc ProfileController Test 작성
  src/test/java/com/server/Puzzle/controller/profile/ProfileControllerTest.java
  src/test/java/com/server/Puzzle/controller/user/UserControllerTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#127 잘못된 검증 방식 수정
  src/test/java/com/server/Puzzle/controller/board/BoardControllerTest.java
Labels: Build Success, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#128 프로필 컨트롤러 테스트 검증식 변경
  src/test/java/com/server/Puzzle/controller/profile/ProfileControllerTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#130 clean build test compile error fix
  src/main/java/com/server/Puzzle/domain/user/domain/User.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#133 Board,Attend 부분 필드 복수일 경우 명사 + s
  src/main/java/com/server/Puzzle/domain/board/dto/request/CorrectionPostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetAllPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/test/java/com/server/Puzzle/controller/board/BoardControllerTest.java
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
Labels: Build Success, 👩🏻‍🚒 Hotfix, ⚡️ Simple, 🧙🏻‍♂️kyungJun

#134 필드 이름 통일
  src/main/java/com/server/Puzzle/domain/user/dto/ProfileUpdateDto.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/test/java/com/server/Puzzle/controller/profile/ProfileControllerTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
  src/test/java/com/server/Puzzle/service/user/UserServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ hyunin

#136 Board 와 Attend 의 변수명,필드명,메소드명 통일화
  src/main/java/com/server/Puzzle/domain/board/controller/BoardController.java
  src/main/java/com/server/Puzzle/domain/board/domain/Board.java
  src/main/java/com/server/Puzzle/domain/board/domain/BoardImage.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/CorrectionPostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/request/PostRequestDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetAllPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostByTagResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/dto/response/GetPostResponseDto.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardCustomRepositoryImpl.java
  src/main/java/com/server/Puzzle/domain/board/repository/BoardFileRepository.java
  src/main/java/com/server/Puzzle/domain/board/service/BoardService.java
  src/main/java/com/server/Puzzle/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Puzzle/domain/user/service/Impl/ProfileServiceImpl.java
  src/main/java/com/server/Puzzle/global/config/dev/GenerateUser.java
  src/test/java/com/server/Puzzle/controller/board/BoardControllerTest.java
  src/test/java/com/server/Puzzle/exception/board/BoardExceptionTest.java
  src/test/java/com/server/Puzzle/service/attend/AttendServiceTest.java
  src/test/java/com/server/Puzzle/service/board/BoardServiceTest.java
  src/test/java/com/server/Puzzle/service/profile/ProfileServiceTest.java
Labels: Build Success, 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️kyungJun
